theme: osuny
paginate: 18
enableRobotsTXT: true
removePathAccents: true
params:
  summary:
    position: hero
  search:
    active: true  
  logo:
    header: "/assets/images/logoheader.png"
    footer: "/assets/images/logofooter.svg"
  

    

